### ISSUE TITLE
Songs

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#1]
## Value statement
As a **musician** 
I need **to see all my songs** 
so that **I can perform them** 
## Description
![6DE18F12-14F1-49F2-87A0-83BD097FEA71_1_105_c](https://user-images.githubusercontent.com/55999008/69429715-7cb63d80-0d34-11ea-9aa6-513573ffacd9.jpeg)
![All songs on one screen](https://user-images.githubusercontent.com/55999008/69541852-74574000-0f8a-11ea-84fe-454e7850e6eb.png)

- It's a long scrolling list of songs (without formated chords)
- the song is shown in plain ChordPro syntax
## Acceptance criteria
- [x] Songs have to be visually separated
- [x] Songs are shown just in plain ChordPro syntax 
- [x] Songs are scrolled vertically
## Tasks
- [x] create a .json file with a hand full of songs in ChordPro format
- [x] create GlobelStyles component
- [x] create song component in storybook
- [x] add song component to App
- [x] Test on tablet and mobile
## Size
small
