### ISSUE TITLE
transpose

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#10]
## Value statement
As a **musician** 
I need **to transpose the chords easily** 
so that **I change the key fast** 
## Acceptance criteria
- [x] with some kind of slider or button the key can be changed
- [x] the changed chords are shown with the lyrics
- [x] when a song in a setlist is displayed, the tranposing is saved in local storage
## Tasks
- [x]  make design for transposing component
- [x] create component for transposing
- [x] create transposing functionality
- [x] implement the transposing functionality in the app
- [x] implement local storage functionality
## Size
medium
