### ISSUE TITLE
set up data base

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#11]
## Value statement
As a **musician** 
I need **to be able to save my settings and everything** 
so that **everything is how I left it when I reopen the app** 
## Description 
setting up a database with mongoDB and connect it with the app
## Acceptance criteria
- [x] there is a mongoDB data base
- [x] example songs are in the data base
- [x] the app gets its songs out of the data base
## Tasks
- [x] setting up a database with mongoDB
- [x] fill data base with example songs in object format (like it comes after parsing with ChordSheetJS)
- [x] setting up a service.js with get function
- [x] implement get function in the app
## Size
large
