### ISSUE TITLE
create new song (chordpro)

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#12]
## Value statement - a requirement, not a solution
As a **musician** 
I need **to add new songs** 
so that **I can play all the songs that are trending** 
## Description 
![BubbleMenuWithListAddSong](https://user-images.githubusercontent.com/55999008/70431404-4a6b4680-1a7d-11ea-8e65-c8615506f976.png)
![AddSong](https://user-images.githubusercontent.com/55999008/70432392-74256d00-1a7f-11ea-9923-97fba703aa98.png)

there is a possibility to add a song in chordpro-format
## Acceptance criteria
- [x] click on a button to open form page
- [x] form page with input field for the song in ChordPro-Format
- [x] on click on the submit-button the song is saved in the db and the user will receive a notation that is now saved
- [x] the song appears in the app without restart
## Tasks

- [ ] create post function for backend
- [x] create form page
- [x] create button to get to the form page
- [x] implement ChordSheetJS for parsing
- [x] implement routing
- [x] implement notation so that the user sees that the new song is saved in the db
- [x] test on mobile and desktop
## Size
large
