### ISSUE TITLE
implement font

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#14]
## Value statement - a requirement, not a solution
As a **musician** 
I need **to see a good looking font style** 
so that **can be more creative** 
## Description 
'Nunito' (or something similar) font is implemented
## Acceptance criteria
- [x] 'Nunito' (or something similar) font is implemented
## Tasks
- [x] find 'Nunito' (or something similar) and where to get it
- [x] implement the song into the app
## Size
small
