### ISSUE TITLE
fuzzy search

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#19]
## Value statement
As a **user** 
I need **to be able to search for songs** 
so that **I can find the songs faster** 
## Description
there is a search fild in the title list
## Acceptance criteria
- [x] input field on top of the songs in the title list
- [x] while typing the songs are shown in the title list
- [x] searching is fuzzy
## Tasks
- [x] create input field on top of the song titles in the title list
- [x] write fuzzy search logic
- [x] implement fuzzy search logic into the app
- [x] test on mobile and desktop
## Size
small
