### ISSUE TITLE
Title list

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#2]
## Value statement
As a **musician** 
I need **to pick a song from a list** 
so that **I can find a song easier** 
## Description 
![43566BB5-B77B-4412-98DF-825F5E4A43E6_1_105_c](https://user-images.githubusercontent.com/55999008/69430244-6b216580-0d35-11ea-81ce-d317190c1282.jpeg)
![Song with songlist](https://user-images.githubusercontent.com/55999008/69616860-95299f00-1037-11ea-9f89-78623e38551f.png)

- on the left hand side is a scrolling list with all songs
- on the right hand side the picked song is shown
- song is still displayed in plain ChordPro syntax
## Acceptance criteria
- [x] first song on the list is selected by default
- [x] title in the title list gets bolder selected
- [x] corresponding song is shown on the right hand side, when a title gets clicked
- [x] the widths of the title list is 1/3 of the display widths, the title breaks into a new line when it is to long
- [x] the list is sorted in alphabetical order
## Tasks
- [x] create songlist component
- [x] add song selection logic
- [x] update storybook
- [x] test on tablet and mobile
- [x] styling
## Size
medium
