### ISSUE TITLE
redesign

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#20]
## Value statement
As a **musician** 
I need **to have a logical and good looking menu** 
so that **I like the app** 
## Description
![circleMenu](https://user-images.githubusercontent.com/55999008/70429717-75539b80-1a79-11ea-9740-cf585a3044d9.png)
## Acceptance criteria
- [x] new design is implemented and working in  the app
## Tasks
- [x] create new design in adobe xd
- [x] implement design into the app
- [x] make functionality work again
- [x] test on mobile and desktop
## Size
small
