### ISSUE TITLE
setlists

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#23]
## Value statement - a requirement, not a solution
As a **musician** 
I need **to have setlists** 
so that **I only have the songs in a list that I need at the moment** 
## Acceptance criteria
- [x] mongo DB collection with setlist
- [x] populate songs into the mongoose schema
- [x] have all navigation components which are needed
- [x] when a setlist gets clicked the corresponding songs show in the list and the first song will be displayed by default
## Tasks
- [x] (todos for the team)
## Size
medium
