### ISSUE TITLE
make addSong stable

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#26]
## Value statement
As a **musician** 
I need **to not accidentally crash my data base** 
so that **my app keeps on working properly** 
## Description
make the functionality of adding a song more stable
## Acceptance criteria
- [x] after clicking on the save button when there is no text at all in the textarea input field the user will receive a feedback that there has to be something in the field
- [x] all necessary Object items are created when just anything is typed into the field
- [x] placeholder says, that there has to be at least a song title
## Tasks
- [x] add pop up for when nothing is in the field and the user hits save
- [x] work out what needs to be done that the app works properly when just anything is typed into the field
- [x] put an example song in the textfield
## Size
small
