### ISSUE TITLE
Add Setlist

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#29]
## Value statement
As a **musician** 
I need **to add setlists** 
so that **I can have more gigs** 
## Description 
![AddSetlist](https://user-images.githubusercontent.com/55999008/71492256-168e7000-2836-11ea-8352-d70c7c1177e8.jpg)

when clicking the +-button in the setlist-view the user can add a setlist
## Acceptance criteria
- [x] after clicking the +-button the sidelist-view changes to the addSetlist-view
- [x] there is an input field for the setlist title and the due date
- [x] for the due date there is a date picker
- [x] the created date is saved automatically
- [x] when clicking save a new setlist is created in the data base
## Tasks
- [x] create form
- [x] implement date picker
- [x] create post function for backend
- [x] combine post logic and save-button
- [x] test on mobile and desktop
## Size
large
