### ISSUE TITLE
Toggle Songlist

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#3]
## Value statement
As a **musician** 
I need **to hide and show the songlist** 
so that **the song has more space on my device** 
## Description 
![0C87E4DA-4285-49D0-8A0A-7E1802F805FF_1_105_c copy](https://user-images.githubusercontent.com/55999008/69432727-8e024880-0d3a-11ea-9390-a150afe229d3.jpg)
- There will be a button [Show songlist] resp. [Hide songlist]
- the songlist can be hidden
## Acceptance criteria
- [x] songlist is hidden by default
- [x] button text changes on click
- [x] toggle songlist on button click
## Tasks
- [x] create Button component
- [x] add toggle logic
- [x] test on tablet and mobile
## Size
medium
