### ISSUE TITLE
chords above text

### ISSUE THREAD

**Issue by anniviz** [anniviz/chordly#4]
## Value statement
As a **musician** 
I need **to see the chords above the text** 
so that **I can easily see where I have to play which chords** 
## Description 
![DB3BAFF3-01C0-4C9D-8E5D-9D400EDB81BC_1_105_c](https://user-images.githubusercontent.com/55999008/69526836-5c23f880-0f6b-11ea-9e58-c5cffef752c2.jpeg)

## Acceptance criteria
- [x] chords are in the right place above the text
- [x] title and artist are ontop of the song
## Tasks
- [ ] integrate ChordSheetJS
- [x] parse song into object
- [x] format the chords into place
- [x] test on desktop and tablet
## Size
large
